[package]
name = "cargo_auto_lib"
version = "1.3.4"
authors = ["Bestia.dev"]
homepage = "https://bestia.dev"
edition = "2021"
description = "Library crate for common tasks when building rust projects. Intended for use with cargo-auto - automation tasks written in Rust language."
repository = "https://github.com/bestia-dev/cargo_auto_lib"
readme = "README.md"
license = "MIT"
keywords = ["maintained","ready-for-use", "rust","cargo-auto"]
categories = ["development-tools::build-utils"]
# publish as a cargo tool. Only this files.
publish = true
include = [
    "Cargo.toml",
    "LICENSE",
    "README.md",
    "src/*",
]

[dependencies]
lazy_static="1.4.0"
regex = "1.10.3"
termion = "3.0.0"
glob = "0.3.1"
chrono="0.4.33"
filetime = "0.2.23"
serde = "1.0.196"
serde_derive = "1.0.196"
serde_json = "1.0.113"
toml = "0.8.9"
anyhow="1.0.79"
cargo_toml = "0.19.1"
reader_for_microxml="2.0.1"
semver="1.0.21"
sha2 = "0.10.8"
base64ct = {version = "1.6.0", features = ["alloc"] }
deflate = "1.0.0"
radix64 = "0.6.2"
reqwest = { version = "0.11.24", features = ["blocking", "stream"] }
ring = "0.17.7"
data-encoding = "2.5.0"
thiserror="1.0.56"
pretty_dbg = "1.0.54"
home = "0.5.9"
inquire = "0.6.2"
ssh2-config = "0.2.3"
tokio-util = {version = "0.7.8", features = ["codec"]}
tokio = {version = "1.28.2", features = ["rt","rt-multi-thread","fs"]}
url="2.3.1"
