[package]
name = "cargo_auto_lib"
version = "0.7.24"
authors = ["Bestia.dev <info@bestia.dev>"]
edition = "2018"
description = "Library crate for common tasks when building rust projects. Intended for use with cargo-auto: automation tasks written in Rust language."
repository = "https://github.com/bestia-dev/cargo_auto_lib"
readme = "README.md"
license = "MIT"
keywords = ["rust","cargo-auto"]
categories = ["development-tools::build-utils"]
# publish as a cargo tool. Only this files.
publish = true
include = [
    "Cargo.toml",
    "LICENSE",
    "README.md",
    "src/*",
]

[dependencies]
unwrap = "1.2.1"
lazy_static="1.4.0"
regex = "1.5.4"
termion = "1.5.6"
glob = "0.3.0"
chrono="0.4.19"
filetime = "0.2.12"
serde = "1.0.115"
serde_derive = "1.0.115"
serde_json = "1.0.57"
toml = "0.5.6"
anyhow="1.0.32"
cargo_toml = "0.9.2"
reader_for_microxml="2.0.1"
semver="1.0.4"