[package]
name = "cargo_auto_lib"
version = "0.7.15"
authors = ["Luciano Bestia <luciano.bestia@gmail.com>"]
edition = "2018"
description = "Library crate for common tasks when building rust projects. Intended for use with cargo-auto: automation tasks written in Rust language."
repository = "https://github.com/LucianoBestia/cargo_auto_lib"
readme = "README.md"
license = "MIT"
keywords = ["rust","cargo-auto"]
categories = ["development-tools::build-utils"]
# publish as a cargo tool. Only this files.
publish = true
include = [
    "Cargo.toml",
    "LICENSE",
    "README.md",
    "src/*",
]

[dependencies]
unwrap = "1.2.1"
lazy_static="1.4.0"
regex = "1.5.4"
termion = "1.5.6"
glob = "0.3.0"
chrono="0.4.19"
filetime = "0.2.12"
serde = "1.0.115"
serde_derive = "1.0.115"
serde_json = "1.0.57"
toml = "0.5.6"
anyhow="1.0.32"
cargo_toml = "0.9.2"
# for github API
octocrab = "0.12.0"
reqwest={version="0.11.4", features=["stream"]}
tokio-util = "0.6.7"
tokio = {version = "1.10.0", features = ["rt","rt-multi-thread","fs"]}
url="2.2.2"